### ISSUE TITLE
Issue with the .devcontainer

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW7#14]
.devcontainer/python/devcontainer.json

The content of this file is wrong.

**Comment by ojha-aditya** [comment]
Is it the same error as last time?

**Comment by HeshamElsaman** [comment]
> Is it the same error as last time?

I guess not. This time the content of the file is totally wrong, it was confused with some .yaml script.

**Comment by ojha-aditya** [comment]
I am able to configure the codespace with default project configuration and run all the basic commands? What exactly is the error you encountered?

**Comment by HeshamElsaman** [comment]
> I am able to configure the codespace with default project configuration and run all the basic commands? What exactly is the error you encountered?

Yeah I did that as well, but just needed to point that out for consistency.
I guess #19 closes this issue.
