### ISSUE TITLE
Typo maybe?

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW7#25]
Why is tanh(x) mentioned twice here?

@laserlab 

![image](https://github.com/user-attachments/assets/4101501b-8631-4539-81d1-e2a937f6a3c0)

**Comment by laserlab** [comment]
This is indeed a typo. Thanks for catching it.v This was supposed to be y(x)=sin(x). I’m changing it without PR.

**Comment by laserlab** [comment]
There was a type in the homework description I merged it without PR @zbpetersbuf
