### ISSUE TITLE
Algo: tangent (2 members)

### ISSUE THREAD

**Issue by laserlab** [ubsuny/CP1-24-HW7#5]
Each algorithm has to be implemented in three ways.

wrapper for scipy implementation (due Wednesday)
pure python implementation (due Friday)
c/c++ implementation using ctypes in python (due Monday)

**Comment by HeshamElsaman** [comment]
@haiderabbas007 
I've finished the first one (both the function and its test). You can review them once I create the PR.
You can proceed to work on the second one after you review the first and modify it according to what you regard as suitable.

**Comment by haiderabbas007** [comment]
So I have to do the pure python implementation of the tangent algorithm only?

**Comment by HeshamElsaman** [comment]
@haiderabbas007 Yes, if that suits you.

**Comment by HeshamElsaman** [comment]
I guess PR #43 should be closing this issue as soon as it's accepted. So, I'll just close it for now just in case.
